export const ROUTE_PATH = {
  LOGIN: '/login',
  REGISTER: '/register',
  VERIFY: '/verify',
  HOME: '/',
  HOME_Page: '/home',
  PROFILE: '/profile/:id',
  PRODUCT_DETAIL: '/product/:id',
  PRODUCT: '/product',
  SERVICE: '/service',
  SHOP: '/shop',
  ORDER: '/order',
  PRODUCT_SHOP_MANAGER: '/shop/product-manager',
  SERVICE_SHOP_MANAGER: '/shop/service-manager',
};